---
- hosts: all
  remote_user: ubuntu
  sudo: yes
  vars:
    openvswitch_deps:
      - linux-headers-3.11.0-12-generic
      - openvswitch-datapath-dkms
      - bridge-utils
    docker_deps:
      - python-software-properties
      - python-apt
      - python-pycurl
  tasks:

    - name: Firewall configuration
      command: ufw allow from 10.10.0.0/16
      tags: firewall config

    - name: Firewall configuration
      command: ufw allow from 192.168.250.0/24
      tags: firewall config

    - name: Enable traffic in firewall
      lineinfile: dest=/etc/default/ufw state=present regexp='DEFAULT_FORWARD_POLICY="(.*)"' line='DEFAULT_FORWARD_POLICY="ACCEPT"'
      tags: firewall config

    - name: Restart firewall
      command: ufw reload
      tags: firewall config

    - name: OpenVSwitch dependencies
      apt: pkg={{ item }} state=latest
      with_items: openvswitch_deps
      tags: network repo

    - name: Install OpenVSwitch
      apt: pkg=openvswitch-switch state=latest update_cache=yes
      tags: network repo

    - name: Copy configuration for bridges and tunnels
      copy: src=../provisioning_scripts/prepare_docker_network.sh dest=/home/ubuntu/prepare_docker_network.sh owner=ubuntu group=ubuntu mode=0755
      tags: network configure

    - name: Configure bridges and tunnels
      command: /home/ubuntu/prepare_docker_network.sh {{host_id}} "{{other_hosts}}"
      tags: network configure

    - name: Copy routes config
      copy: src=../provisioning_scripts/route_docker_network.sh dest=/home/ubuntu/route_docker_network.sh owner=ubuntu group=ubuntu mode=0755
      tags: network configure

    - name: Configure docker routes
      command: /home/ubuntu/route_docker_network.sh
      tags: network configure

    - name: Docker dependencies
      apt: pkg={{ item }} state=latest
      with_items: docker_deps
      tags: docker repo

    - name: Add docker repository key
      apt_key: url=https://get.docker.io/gpg state=present
      tags: docker repo

    - name: Add docker repository
      apt_repository: repo='deb http://get.docker.io/ubuntu docker main' state=present
      tags: docker repo

    - name: Install docker
      apt: pkg=lxc-docker state=latest update_cache=yes
      tags: docker repo

